CREATE TABLE `jTrade_dev`.`EquityQuote` (
  `symbol` VARCHAR(45) NOT NULL,
  `time` DATETIME NOT NULL,
  `price` FLOAT NULL,
  `change` FLOAT NULL,
  `pct_change` FLOAT NULL,
  `volume` FLOAT NULL,
  `avg_volume` FLOAT NULL,
  `name` VARCHAR(45) NULL,
  `exchange` VARCHAR(45) NULL,
  `market_cap` FLOAT NULL,
  `day_high` FLOAT NULL,
  `day_low` FLOAT NULL,
  `year_high` FLOAT NULL,
  `year_low` FLOAT NULL,
  PRIMARY KEY (`symbol`, `time`));


CREATE TABLE `jTrade_dev`.`Position` (
  `symbol` VARCHAR(45) NOT NULL,
  `date` DATE NOT NULL,
  `share` FLOAT NOT NULL,
  `price` FLOAT NOT NULL,
  `value` FLOAT NULL,
  `cost` FLOAT NULL,
  `pct_ret` FLOAT NULL,
  `abs_ret` FLOAT NULL,
  PRIMARY KEY (`symbol`, `date`));


CREATE TABLE `jTrade_dev`.`Order` (
  `symbol` VARCHAR(45) NOT NULL,
  `date` DATE NOT NULL,
  `share` FLOAT NULL,
  `price` FLOAT NULL,
  `fee` FLOAT NULL,
  `total` FLOAT NULL,
  PRIMARY KEY (`symbol`, `date`));


CREATE TABLE `jTrade_dev`.`EquityHP` (
  `symbol` VARCHAR(45) NOT NULL,
  `date` DATE NOT NULL,
  `open` FLOAT NULL,
  `high` FLOAT NULL,
  `low` FLOAT NULL,
  `close` FLOAT NULL,
  `volume` FLOAT NULL,
  `ex_dividend` FLOAT NULL,
  `split_ratio` FLOAT NULL,
  `adj_open` FLOAT NULL,
  `adj_high` FLOAT NULL,
  `adj_low` FLOAT NULL,
  `adj_close` FLOAT NULL,
  `adj_volume` FLOAT NULL,
  PRIMARY KEY (`symbol`, `date`));


CREATE TABLE `jTrade_dev`.`EquityInd` (
  `symbol` VARCHAR(45) NOT NULL,
  `date` DATE NOT NULL,
  `indicator` VARCHAR(45) NOT NULL,
  `val` FLOAT NULL,
  PRIMARY KEY (`symbol`, `date`, `indicator`));


CREATE TABLE `jTrade_dev`.`EquityFinIS` (
  `symbol` VARCHAR(45) NOT NULL,
  `year` INT NOT NULL,
  `period` VARCHAR(45) NOT NULL,
  `operatingrevenue` FLOAT NULL,
  `totalrevenue` FLOAT NULL,
  `operatingcostofrevenue` FLOAT NULL,
  `totalcostofrevenue` FLOAT NULL,
  `totalgrossprofit` FLOAT NULL,
  `sgaexpense` FLOAT NULL,
  `rdexpense` FLOAT NULL,
  `totaloperatingexpenses` FLOAT NULL,
  `totaloperatingincome` FLOAT NULL,
  `otherincome` FLOAT NULL,
  `totalotherincome` FLOAT NULL,
  `totalpretaxincome` FLOAT NULL,
  `incometaxexpense` FLOAT NULL,
  `netincomecontinuing` FLOAT NULL,
  `netincome` FLOAT NULL,
  `netincometocommon` FLOAT NULL,
  `weightedavebasicsharesos` FLOAT NULL,
  `basiceps` FLOAT NULL,
  `weightedavedilutedsharesos` FLOAT NULL,
  `dilutedeps` FLOAT NULL,
  `weightedavebasicdilutedsharesos` FLOAT NULL,
  `basicdilutedeps` FLOAT NULL,
  `cashdividendspershare` FLOAT NULL,
  PRIMARY KEY (`symbol`, `year`, `period`));


CREATE TABLE `jTrade_dev`.`EquityFinBS` (
  `symbol` VARCHAR(45) NOT NULL,
  `year` INT NOT NULL,
  `period` VARCHAR(45) NOT NULL,
  `cashandequivalents` FLOAT NULL,
  `shortterminvestments` FLOAT NULL,
  `notereceivable` FLOAT NULL,
  `accountsreceivable` FLOAT NULL,
  `netinventory` FLOAT NULL,
  `othercurrentassets` FLOAT NULL,
  `totalcurrentassets` FLOAT NULL,
  `netppe` FLOAT NULL,
  `longterminvestments` FLOAT NULL,
  `goodwill` FLOAT NULL,
  `intangibleassets` FLOAT NULL,
  `othernoncurrentassets` FLOAT NULL,
  `totalnoncurrentassets` FLOAT NULL,
  `totalassets` FLOAT NULL,
  `shorttermdebt` FLOAT NULL,
  `accountspayable` FLOAT NULL,
  `accruedexpenses` FLOAT NULL,
  `totalcurrentliabilities` FLOAT NULL,
  `longtermdebt` FLOAT NULL,
  `othernoncurrentliabilities` FLOAT NULL,
  `totalnoncurrentliabilities` FLOAT NULL,
  `totalliabilities` FLOAT NULL,
  `commitmentsandcontingencies` FLOAT NULL,
  `commonequity` FLOAT NULL,
  `retainedearnings` FLOAT NULL,
  `aoci` FLOAT NULL,
  `totalcommonequity` FLOAT NULL,
  `totalequity` FLOAT NULL,
  `totalequityandnoncontrollinginterests` FLOAT NULL,
  `totalliabilitiesandequity` FLOAT NULL,
  `currentdeferredrevenue` FLOAT NULL,
  `noncurrentdeferredrevenue` FLOAT NULL,
  `currentdeferredtaxassets` FLOAT NULL,
  PRIMARY KEY (`symbol`, `year`, `period`));


CREATE TABLE `jTrade_dev`.`EquityFinCF` (
  `symbol` VARCHAR(45) NOT NULL,
  `year` INT NOT NULL,
  `period` VARCHAR(45) NOT NULL,
  `netincome` FLOAT NULL,
  `netincomecontinuing` FLOAT NULL,
  `depreciationexpense` FLOAT NULL,
  `noncashadjustmentstonetincome` FLOAT NULL,
  `increasedecreaseinoperatingcapital` FLOAT NULL,
  `netcashfromcontinuingoperatingactivities` FLOAT NULL,
  `netcashfromoperatingactivities` FLOAT NULL,
  `purchaseofplantpropertyandequipment` FLOAT NULL,
  `acquisitions` FLOAT NULL,
  `purchaseofinvestments` FLOAT NULL,
  `saleofinvestments` FLOAT NULL,
  `otherinvestingactivitiesnet` FLOAT NULL,
  `netcashfromcontinuinginvestingactivities` FLOAT NULL,
  `netcashfrominvestingactivities` FLOAT NULL,
  `repurchaseofcommonequity` FLOAT NULL,
  `paymentofdividends` FLOAT NULL,
  `issuanceofdebt` FLOAT NULL,
  `repaymentofdebt` FLOAT NULL,
  `issuanceofcommonequity` FLOAT NULL,
  `otherfinancingactivitiesnet` FLOAT NULL,
  `netcashfromcontinuingfinancingactivities` FLOAT NULL,
  `netcashfromfinancingactivities` FLOAT NULL,
  `netchangeincash` FLOAT NULL,
  `cashinterestpaid` FLOAT NULL,
  `cashincometaxespaid` FLOAT NULL,
  PRIMARY KEY (`symbol`, `year`, `period`));


CREATE TABLE `jTrade_dev`.`EquityFinFund` (
  `symbol` VARCHAR(45) NOT NULL,
  `year` INT NOT NULL,
  `period` VARCHAR(45) NOT NULL,
  `revenuegrowth` FLOAT NULL,
  `nopat` FLOAT NULL,
  `nopatmargin` FLOAT NULL,
  `investedcapital` FLOAT NULL,
  `investedcapitalturnover` FLOAT NULL,
  `investedcapitalincreasedecrease` FLOAT NULL,
  `freecashflow` FLOAT NULL,
  `netnonopex` FLOAT NULL,
  `netnonopobligations` FLOAT NULL,
  `ebit` FLOAT NULL,
  `depreciationandamortization` FLOAT NULL,
  `ebitda` FLOAT NULL,
  `capex` FLOAT NULL,
  `dfcfnwc` FLOAT NULL,
  `dfnwc` FLOAT NULL,
  `nwc` FLOAT NULL,
  `debt` FLOAT NULL,
  `ltdebtandcapleases` FLOAT NULL,
  `netdebt` FLOAT NULL,
  `totalcapital` FLOAT NULL,
  `bookvaluepershare` FLOAT NULL,
  `tangbookvaluepershare` FLOAT NULL,
  `marketcap` FLOAT NULL,
  `enterprisevalue` FLOAT NULL,
  `pricetobook` FLOAT NULL,
  `pricetotangiblebook` FLOAT NULL,
  `pricetorevenue` FLOAT NULL,
  `pricetoearnings` FLOAT NULL,
  `dividendyield` FLOAT NULL,
  `earningsyield` FLOAT NULL,
  `evtoinvestedcapital` FLOAT NULL,
  `evtorevenue` FLOAT NULL,
  `evtoebitda` FLOAT NULL,
  `evtoebit` FLOAT NULL,
  `evtonopat` FLOAT NULL,
  `evtoocf` FLOAT NULL,
  `evtofcff` FLOAT NULL,
  `ebitdagrowth` FLOAT NULL,
  `ebitgrowth` FLOAT NULL,
  `nopatgrowth` FLOAT NULL,
  `netincomegrowth` FLOAT NULL,
  `epsgrowth` FLOAT NULL,
  `ocfgrowth` FLOAT NULL,
  `fcffgrowth` FLOAT NULL,
  `investedcapitalgrowth` FLOAT NULL,
  `revenueqoqgrowth` FLOAT NULL,
  `ebitdaqoqgrowth` FLOAT NULL,
  `ebitqoqgrowth` FLOAT NULL,
  `nopatqoqgrowth` FLOAT NULL,
  `netincomeqoqgrowth` FLOAT NULL,
  `epsqoqgrowth` FLOAT NULL,
  `ocfqoqgrowth` FLOAT NULL,
  `fcffqoqgrowth` FLOAT NULL,
  `investedcapitalqoqgrowth` FLOAT NULL,
  `grossmargin` FLOAT NULL,
  `ebitdamargin` FLOAT NULL,
  `operatingmargin` FLOAT NULL,
  `ebitmargin` FLOAT NULL,
  `profitmargin` FLOAT NULL,
  `costofrevtorevenue` FLOAT NULL,
  `sgaextorevenue` FLOAT NULL,
  `rdextorevenue` FLOAT NULL,
  `opextorevenue` FLOAT NULL,
  `taxburdenpct` FLOAT NULL,
  `interestburdenpct` FLOAT NULL,
  `efftaxrate` FLOAT NULL,
  `assetturnover` FLOAT NULL,
  `arturnover` FLOAT NULL,
  `invturnover` FLOAT NULL,
  `faturnover` FLOAT NULL,
  `apturnover` FLOAT NULL,
  `dso` FLOAT NULL,
  `dio` FLOAT NULL,
  `dpo` FLOAT NULL,
  `ccc` FLOAT NULL,
  `finleverage` FLOAT NULL,
  `leverageratio` FLOAT NULL,
  `compoundleveragefactor` FLOAT NULL,
  `ltdebttoequity` FLOAT NULL,
  `debttoequity` FLOAT NULL,
  `roic` FLOAT NULL,
  `nnep` FLOAT NULL,
  `roicnnepspread` FLOAT NULL,
  `rnnoa` FLOAT NULL,
  `roe` FLOAT NULL,
  `croic` FLOAT NULL,
  `oroa` FLOAT NULL,
  `roa` FLOAT NULL,
  `noncontrollinginterestsharingratio` FLOAT NULL,
  `roce` FLOAT NULL,
  `divpayoutratio` FLOAT NULL,
  `augmentedpayoutratio` FLOAT NULL,
  `ocftocapex` FLOAT NULL,
  `stdebttocap` FLOAT NULL,
  `ltdebttocap` FLOAT NULL,
  `debttototalcapital` FLOAT NULL,
  `preferredtocap` FLOAT NULL,
  `noncontrolinttocap` FLOAT NULL,
  `commontocap` FLOAT NULL,
  `debttoebitda` FLOAT NULL;

  PRIMARY KEY (`symbol`, `year`, `period`));
