CREATE TABLE `jTrade_dev`.`EquityInfo` (
  `symbol` VARCHAR(45) NOT NULL,
  `name` VARCHAR(45) NULL,
  `sector` VARCHAR(45) NULL,
  `industry` VARCHAR(45) NULL,
  `summary` TEXT NULL,
  PRIMARY KEY (`symbol`));


CREATE TABLE `jTrade_dev`.`EquityQuote` (
  `symbol` VARCHAR(45) NOT NULL,
  `time` DATETIME NOT NULL,
  `price` FLOAT NULL,
  `change` FLOAT NULL,
  `pct_change` FLOAT NULL,
  `volume` FLOAT NULL,
  `avg_volume` FLOAT NULL,
  `name` VARCHAR(45) NULL,
  `exchange` VARCHAR(45) NULL,
  `market_cap` FLOAT NULL,
  `day_high` FLOAT NULL,
  `day_low` FLOAT NULL,
  `year_high` FLOAT NULL,
  `year_low` FLOAT NULL,
  PRIMARY KEY (`symbol`, `time`));


CREATE TABLE `jTrade_dev`.`Position` (
  `symbol` VARCHAR(45) NOT NULL,
  `date` DATE NOT NULL,
  `share` FLOAT NOT NULL,
  `price` FLOAT NOT NULL,
  `value` FLOAT NULL,
  `cost` FLOAT NULL,
  `pct_ret` FLOAT NULL,
  `abs_ret` FLOAT NULL,
  PRIMARY KEY (`symbol`, `date`));


CREATE TABLE `jTrade_dev`.`Order` (
  `symbol` VARCHAR(45) NOT NULL,
  `date` DATE NOT NULL,
  `share` FLOAT NULL,
  `price` FLOAT NULL,
  `fee` FLOAT NULL,
  `total` FLOAT NULL,
  PRIMARY KEY (`symbol`, `date`));


CREATE TABLE `jTrade_dev`.`EquityHP` (
  `symbol` VARCHAR(45) NOT NULL,
  `date` DATE NOT NULL,
  `open` FLOAT NULL,
  `high` FLOAT NULL,
  `low` FLOAT NULL,
  `close` FLOAT NULL,
  `volume` FLOAT NULL,
  `ex_dividend` FLOAT NULL,
  `split_ratio` FLOAT NULL,
  `adj_open` FLOAT NULL,
  `adj_high` FLOAT NULL,
  `adj_low` FLOAT NULL,
  `adj_close` FLOAT NULL,
  `adj_volume` FLOAT NULL,
  PRIMARY KEY (`symbol`, `date`));


CREATE TABLE `jTrade_dev`.`EquityInd` (
  `symbol` VARCHAR(45) NOT NULL,
  `date` DATE NOT NULL,
  `indicator` VARCHAR(45) NOT NULL,
  `val` FLOAT NULL,
  PRIMARY KEY (`symbol`, `date`, `indicator`));


CREATE TABLE `jTrade_dev`.`EquityFinIS` (
  `symbol` VARCHAR(45) NOT NULL,
  `year` INT NOT NULL,
  `period` VARCHAR(45) NOT NULL,
  `operatingrevenue` FLOAT NULL,
  `loansandleaseinterestincome` FLOAT NULL,
  `investmentsecuritiesinterestincome` FLOAT NULL,
  `depositsinterestincome` FLOAT NULL,
  `fedfundsandrepointerestincome` FLOAT NULL,
  `tradingaccountinterestincome` FLOAT NULL,
  `otherinterestincome` FLOAT NULL,
  `depositsinterestexpense` FLOAT NULL,
  `shorttermborrowinginterestexpense` FLOAT NULL,
  `longtermdebtinterestexpense` FLOAT NULL,
  `fedfundsandrepointerestexpense` FLOAT NULL,
  `capitalizedleaseobligationinterestexpense` FLOAT NULL,
  `otherinterestexpense` FLOAT NULL,
  `netinterestincome` FLOAT NULL,
  `trustfeeincome` FLOAT NULL,
  `servicechargesondepositsincome` FLOAT NULL,
  `otherservicechargeincome` FLOAT NULL,
  `netrealizedcapitalgains` FLOAT NULL,
  `premiumsearned` FLOAT NULL,
  `investmentbankingincome` FLOAT NULL,
  `othernoninterestincome` FLOAT NULL,
  `totalnoninterestincome` FLOAT NULL,
  `otherrevenue` FLOAT NULL,
  `totalrevenue` FLOAT NULL,
  `operatingcostofrevenue` FLOAT NULL,
  `othercostofrevenue` FLOAT NULL,
  `totalcostofrevenue` FLOAT NULL,
  `totalgrossprofit` FLOAT NULL,
  `sgaexpense` FLOAT NULL,
  `salariesandemployeebenefitsexpense` FLOAT NULL,
  `marketingexpense` FLOAT NULL,
  `rdexpense` FLOAT NULL,
  `provisionforcreditlosses` FLOAT NULL,
  `netoccupancyequipmentexpense` FLOAT NULL,
  `explorationexpense` FLOAT NULL,
  `propertyliabilityinsuranceclaims` FLOAT NULL,
  `policyacquisitioncosts` FLOAT NULL,
  `amortizationofdeferredpolicyacquisitioncosts` FLOAT NULL,
  `currentandfuturebenefits` FLOAT NULL,
  `depreciationexpense` FLOAT NULL,
  `amortizationexpense` FLOAT NULL,
  `depletionexpense` FLOAT NULL,
  `otheroperatingexpenses` FLOAT NULL,
  `impairmentexpense` FLOAT NULL,
  `restructuringcharge` FLOAT NULL,
  `otherspecialcharges` FLOAT NULL,
  `totalnoninterestexpense` FLOAT NULL,
  `totaloperatingexpenses` FLOAT NULL,
  `totaloperatingincome` FLOAT NULL,
  `totalinterestexpense` FLOAT NULL,
  `totalinterestincome` FLOAT NULL,
  `otherincome` FLOAT NULL,
  `totalotherincome` FLOAT NULL,
  `nonoperatingincome` FLOAT NULL,
  `totalpretaxincome` FLOAT NULL,
  `incometaxexpense` FLOAT NULL,
  `othergains` FLOAT NULL,
  `netincomecontinuing` FLOAT NULL,
  `netincomediscontinued` FLOAT NULL,
  `extraordinaryincome` FLOAT NULL,
  `otheradjustmentstoconsolidatednetincome` FLOAT NULL,
  `netincome` FLOAT NULL,
  `preferreddividends` FLOAT NULL,
  `netincometononcontrollinginterest` FLOAT NULL,
  `otheradjustmentstonetincometocommon` FLOAT NULL,
  `netincometocommon` FLOAT NULL,
  `weightedavebasicsharesos` FLOAT NULL,
  `basiceps` FLOAT NULL,
  `weightedavedilutedsharesos` FLOAT NULL,
  `dilutedeps` FLOAT NULL,
  `weightedavebasicdilutedsharesos` FLOAT NULL,
  `basicdilutedeps` FLOAT NULL,
  `cashdividendspershare` FLOAT NULL,
  PRIMARY KEY (`symbol`, `year`, `period`));


CREATE TABLE `jTrade_dev`.`EquityFinBS` (
  `symbol` VARCHAR(45) NOT NULL,
  `year` INT NOT NULL,
  `period` VARCHAR(45) NOT NULL,
  `cashandequivalents` FLOAT NULL,
  `restrictedcash` FLOAT NULL,
  `fedfundssold` FLOAT NULL,
  `interestbearingdepositsatotherbanks` FLOAT NULL,
  `timedepositsplaced` FLOAT NULL,
  `tradingaccountsecurities` FLOAT NULL,
  `shortterminvestments` FLOAT NULL,
  `loansandleases` FLOAT NULL,
  `allowanceforloanandleaselosses` FLOAT NULL,
  `netloansandleases` FLOAT NULL,
  `loansheldforsale` FLOAT NULL,
  `accruedinvestmentincome` FLOAT NULL,
  `notereceivable` FLOAT NULL,
  `accountsreceivable` FLOAT NULL,
  `customerandotherreceivables` FLOAT NULL,
  `netpremisesandequipment` FLOAT NULL,
  `netinventory` FLOAT NULL,
  `prepaidexpenses` FLOAT NULL,
  `currentdeferredtaxassets` FLOAT NULL,
  `othercurrentassets` FLOAT NULL,
  `othercurrentnonoperatingassets` FLOAT NULL,
  `totalcurrentassets` FLOAT NULL,
  `grossppe` FLOAT NULL,
  `accumulateddepreciation` FLOAT NULL,
  `netppe` FLOAT NULL,
  `longterminvestments` FLOAT NULL,
  `noncurrentnotereceivables` FLOAT NULL,
  `goodwill` FLOAT NULL,
  `intangibleassets` FLOAT NULL,
  `noncurrentdeferredtaxassets` FLOAT NULL,
  `employeebenefitassets` FLOAT NULL,
  `mortgageservicingrights` FLOAT NULL,
  `unearnedpremiumsdebit` FLOAT NULL,
  `deferredacquisitioncost` FLOAT NULL,
  `separateaccountbusinessassets` FLOAT NULL,
  `othernoncurrentassets` FLOAT NULL,
  `othernoncurrentnonoperatingassets` FLOAT NULL,
  `totalnoncurrentassets` FLOAT NULL,
  `otherassets` FLOAT NULL,
  `totalassets` FLOAT NULL,
  `shorttermdebt` FLOAT NULL,
  `noninterestbearingdeposits` FLOAT NULL,
  `interestbearingdeposits` FLOAT NULL,
  `fedfundspurchased` FLOAT NULL,
  `bankersacceptances` FLOAT NULL,
  `accountspayable` FLOAT NULL,
  `othershorttermpayables` FLOAT NULL,
  `accruedinterestpayable` FLOAT NULL,
  `accruedexpenses` FLOAT NULL,
  `customerdeposits` FLOAT NULL,
  `dividendspayable` FLOAT NULL,
  `currentdeferredrevenue` FLOAT NULL,
  `currentdeferredtaxliabilities` FLOAT NULL,
  `currentemployeebenefitliabilities` FLOAT NULL,
  `othertaxespayable` FLOAT NULL,
  `othercurrentliabilities` FLOAT NULL,
  `othercurrentnonoperatingliabilities` FLOAT NULL,
  `totalcurrentliabilities` FLOAT NULL,
  `longtermdebt` FLOAT NULL,
  `capitalleaseobligations` FLOAT NULL,
  `claimsandclaimexpenses` FLOAT NULL,
  `futurepolicybenefits` FLOAT NULL,
  `assetretirementandlitigationobligation` FLOAT NULL,
  `unearnedpremiumscredit` FLOAT NULL,
  `policyholderfunds` FLOAT NULL,
  `participatingpolicyholderequity` FLOAT NULL,
  `separateaccountbusinessliabilities` FLOAT NULL,
  `noncurrentdeferredrevenue` FLOAT NULL,
  `noncurrentdeferredtaxliabilities` FLOAT NULL,
  `noncurrentemployeebenefitliabilities` FLOAT NULL,
  `othernoncurrentliabilities` FLOAT NULL,
  `othernoncurrentnonoperatingliabilities` FLOAT NULL,
  `otherlongtermliabilities` FLOAT NULL,
  `totalnoncurrentliabilities` FLOAT NULL,
  `totalliabilities` FLOAT NULL,
  `commitmentsandcontingencies` FLOAT NULL,
  `redeemablenoncontrollinginterest` FLOAT NULL,
  `totalpreferredequity` FLOAT NULL,
  `commonequity` FLOAT NULL,
  `retainedearnings` FLOAT NULL,
  `treasurystock` FLOAT NULL,
  `aoci` FLOAT NULL,
  `otherequity` FLOAT NULL,
  `totalcommonequity` FLOAT NULL,
  `totalequity` FLOAT NULL,
  `noncontrollinginterests` FLOAT NULL,
  `totalequityandnoncontrollinginterests` FLOAT NULL,
  `totalliabilitiesandequity` FLOAT NULL,
  PRIMARY KEY (`symbol`, `year`, `period`));


CREATE TABLE `jTrade_dev`.`EquityFinCF` (
  `symbol` VARCHAR(45) NOT NULL,
  `year` INT NOT NULL,
  `period` VARCHAR(45) NOT NULL,
  `netincome` FLOAT NULL,
  `netincomediscontinued` FLOAT NULL,
  `netincomecontinuing` FLOAT NULL,
  `provisionforloanlosses` FLOAT NULL,
  `depreciationexpense` FLOAT NULL,
  `amortizationexpense` FLOAT NULL,
  `noncashadjustmentstonetincome` FLOAT NULL,
  `increasedecreaseinoperatingcapital` FLOAT NULL,
  `netcashfromcontinuingoperatingactivities` FLOAT NULL,
  `netcashfromdiscontinuedoperatingactivities` FLOAT NULL,
  `netcashfromoperatingactivities` FLOAT NULL,
  `purchaseofplantpropertyandequipment` FLOAT NULL,
  `acquisitions` FLOAT NULL,
  `purchaseofinvestments` FLOAT NULL,
  `saleofplantpropertyandequipment` FLOAT NULL,
  `divestitures` FLOAT NULL,
  `saleofinvestments` FLOAT NULL,
  `netincreaseinfedfundssold` FLOAT NULL,
  `loansheldforsalenet` FLOAT NULL,
  `otherinvestingactivitiesnet` FLOAT NULL,
  `netcashfromcontinuinginvestingactivities` FLOAT NULL,
  `netcashfromdiscontinuedinvestingactivities` FLOAT NULL,
  `netcashfrominvestingactivities` FLOAT NULL,
  `netchangeindeposits` FLOAT NULL,
  `issuanceofdebt` FLOAT NULL,
  `issuanceofpreferredequity` FLOAT NULL,
  `issuanceofcommonequity` FLOAT NULL,
  `repaymentofdebt` FLOAT NULL,
  `repurchaseofpreferredequity` FLOAT NULL,
  `repurchaseofcommonequity` FLOAT NULL,
  `paymentofdividends` FLOAT NULL,
  `otherfinancingactivitiesnet` FLOAT NULL,
  `netcashfromcontinuingfinancingactivities` FLOAT NULL,
  `netcashfromdiscontinuedfinancingactivities` FLOAT NULL,
  `netcashfromfinancingactivities` FLOAT NULL,
  `effectofexchangeratechanges` FLOAT NULL,
  `othernetchangesincash` FLOAT NULL,
  `netchangeincash` FLOAT NULL,
  `cashinterestpaid` FLOAT NULL,
  `cashinterestreceived` FLOAT NULL,
  `cashincometaxespaid` FLOAT NULL,
  PRIMARY KEY (`symbol`, `year`, `period`));


CREATE TABLE `jTrade_dev`.`EquityFinFund` (
  `symbol` VARCHAR(45) NOT NULL,
  `year` INT NOT NULL,
  `period` VARCHAR(45) NOT NULL,
  `altmanzscore` FLOAT NULL,
  `apturnover` FLOAT NULL,
  `arturnover` FLOAT NULL,
  `assetturnover` FLOAT NULL,
  `augmentedpayoutratio` FLOAT NULL,
  `bookvaluepershare` FLOAT NULL,
  `capex` FLOAT NULL,
  `ccc` FLOAT NULL,
  `commontocap` FLOAT NULL,
  `compoundleveragefactor` FLOAT NULL,
  `costofrevtorevenue` FLOAT NULL,
  `croic` FLOAT NULL,
  `currentratio` FLOAT NULL,
  `debt` FLOAT NULL,
  `debttoebitda` FLOAT NULL,
  `debttoequity` FLOAT NULL,
  `debttonopat` FLOAT NULL,
  `debttototalcapital` FLOAT NULL,
  `depreciationandamortization` FLOAT NULL,
  `dfcfnwc` FLOAT NULL,
  `dfcfnwctorev` FLOAT NULL,
  `dfnwc` FLOAT NULL,
  `dfnwctorev` FLOAT NULL,
  `dio` FLOAT NULL,
  `dividendyield` FLOAT NULL,
  `divpayoutratio` FLOAT NULL,
  `dpo` FLOAT NULL,
  `dso` FLOAT NULL,
  `earningsyield` FLOAT NULL,
  `ebit` FLOAT NULL,
  `ebitda` FLOAT NULL,
  `ebitdagrowth` FLOAT NULL,
  `ebitdamargin` FLOAT NULL,
  `ebitdaqoqgrowth` FLOAT NULL,
  `ebitgrowth` FLOAT NULL,
  `ebitlesscapextointerestex` FLOAT NULL,
  `ebitmargin` FLOAT NULL,
  `ebitqoqgrowth` FLOAT NULL,
  `ebittointerestex` FLOAT NULL,
  `efftaxrate` FLOAT NULL,
  `enterprisevalue` FLOAT NULL,
  `epsgrowth` FLOAT NULL,
  `epsqoqgrowth` FLOAT NULL,
  `evtoebit` FLOAT NULL,
  `evtoebitda` FLOAT NULL,
  `evtofcff` FLOAT NULL,
  `evtoinvestedcapital` FLOAT NULL,
  `evtonopat` FLOAT NULL,
  `evtoocf` FLOAT NULL,
  `evtorevenue` FLOAT NULL,
  `faturnover` FLOAT NULL,
  `fcffgrowth` FLOAT NULL,
  `fcffqoqgrowth` FLOAT NULL,
  `fcfftointerestex` FLOAT NULL,
  `finleverage` FLOAT NULL,
  `freecashflow` FLOAT NULL,
  `grossmargin` FLOAT NULL,
  `interestburdenpct` FLOAT NULL,
  `investedcapital` FLOAT NULL,
  `investedcapitalgrowth` FLOAT NULL,
  `investedcapitalincreasedecrease` FLOAT NULL,
  `investedcapitalqoqgrowth` FLOAT NULL,
  `investedcapitalturnover` FLOAT NULL,
  `invturnover` FLOAT NULL,
  `leverageratio` FLOAT NULL,
  `ltdebtandcapleases` FLOAT NULL,
  `ltdebttocap` FLOAT NULL,
  `ltdebttoebitda` FLOAT NULL,
  `ltdebttoequity` FLOAT NULL,
  `ltdebttonopat` FLOAT NULL,
  `marketcap` FLOAT NULL,
  `netdebt` FLOAT NULL,
  `netdebttoebitda` FLOAT NULL,
  `netdebttonopat` FLOAT NULL,
  `netincomegrowth` FLOAT NULL,
  `netincomeqoqgrowth` FLOAT NULL,
  `netnonopex` FLOAT NULL,
  `netnonopobligations` FLOAT NULL,
  `nnep` FLOAT NULL,
  `noncontrolinttocap` FLOAT NULL,
  `noncontrollinginterestsharingratio` FLOAT NULL,
  `nopat` FLOAT NULL,
  `nopatgrowth` FLOAT NULL,
  `nopatlesscapextointex` FLOAT NULL,
  `nopatmargin` FLOAT NULL,
  `nopatqoqgrowth` FLOAT NULL,
  `nopattointerestex` FLOAT NULL,
  `normalizednopat` FLOAT NULL,
  `normalizednopatmargin` FLOAT NULL,
  `nwc` FLOAT NULL,
  `nwctorev` FLOAT NULL,
  `ocfgrowth` FLOAT NULL,
  `ocflesscapextointerestex` FLOAT NULL,
  `ocfqoqgrowth` FLOAT NULL,
  `ocftocapex` FLOAT NULL,
  `ocftointerestex` FLOAT NULL,
  `operatingmargin` FLOAT NULL,
  `opextorevenue` FLOAT NULL,
  `oroa` FLOAT NULL,
  `preferredtocap` FLOAT NULL,
  `pretaxincomemargin` FLOAT NULL,
  `pricetobook` FLOAT NULL,
  `pricetoearnings` FLOAT NULL,
  `pricetorevenue` FLOAT NULL,
  `pricetotangiblebook` FLOAT NULL,
  `profitmargin` FLOAT NULL,
  `quickratio` FLOAT NULL,
  `rdextorevenue` FLOAT NULL,
  `revenuegrowth` FLOAT NULL,
  `revenueqoqgrowth` FLOAT NULL,
  `rnnoa` FLOAT NULL,
  `roa` FLOAT NULL,
  `roce` FLOAT NULL,
  `roe` FLOAT NULL,
  `roic` FLOAT NULL,
  `roicnnepspread` FLOAT NULL,
  `sgaextorevenue` FLOAT NULL,
  `stdebttocap` FLOAT NULL,
  `tangbookvaluepershare` FLOAT NULL,
  `taxburdenpct` FLOAT NULL,
  `totalcapital` FLOAT NULL,
  PRIMARY KEY (`symbol`, `year`, `period`));
